Ultralytics 8.3.25 ðŸš€ Python-3.11.10 torch-2.5.1+cu124 CUDA:0 (NVIDIA A100-SXM4-80GB, 81156MiB)
YOLO11m-cls summary (fused): 138 layers, 10,344,194 parameters, 0 gradients, 39.3 GFLOPs
[34m[1mtrain:[0m /home/datpham/datpham/ACNE11-Classification/datasets/train... found 3525 images in 12 classes âœ… 
[34m[1mval:[0m /home/datpham/datpham/ACNE11-Classification/datasets/val... found 235 images in 12 classes âœ… 
[34m[1mtest:[0m None...

[34m[1mval: [0mScanning /home/datpham/datpham/ACNE11-Classification/datasets/val... 235 images, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 235/235 [00:00<?, ?it/s]
[34m[1mval: [0mScanning /home/datpham/datpham/ACNE11-Classification/datasets/val... 235 images, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 235/235 [00:00<?, ?it/s]

               classes   top1_acc   top5_acc:   0%|          | 0/15 [00:00<?, ?it/s]
               classes   top1_acc   top5_acc:   7%|â–‹         | 1/15 [00:00<00:12,  1.08it/s]
               classes   top1_acc   top5_acc:  13%|â–ˆâ–Ž        | 2/15 [00:01<00:10,  1.26it/s]
               classes   top1_acc   top5_acc:  20%|â–ˆâ–ˆ        | 3/15 [00:01<00:06,  1.96it/s]
               classes   top1_acc   top5_acc:  27%|â–ˆâ–ˆâ–‹       | 4/15 [00:02<00:04,  2.37it/s]
               classes   top1_acc   top5_acc:  47%|â–ˆâ–ˆâ–ˆâ–ˆâ–‹     | 7/15 [00:02<00:01,  5.28it/s]
               classes   top1_acc   top5_acc:  67%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹   | 10/15 [00:02<00:00,  8.13it/s]
               classes   top1_acc   top5_acc:  80%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  | 12/15 [00:02<00:00,  8.59it/s]
               classes   top1_acc   top5_acc: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 15/15 [00:02<00:00,  9.52it/s]
               classes   top1_acc   top5_acc: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 15/15 [00:02<00:00,  5.25it/s]
Traceback (most recent call last):
  File "/home/datpham/.conda/envs/plant/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/cfg/__init__.py", line 826, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/engine/model.py", line 635, in val
    validator(model=self.model)
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/engine/validator.py", line 200, in __call__
    self.finalize_metrics()
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/models/yolo/classify/val.py", line 64, in finalize_metrics
    self.confusion_matrix.process_cls_preds(self.pred, self.targets)
  File "/home/datpham/.conda/envs/plant/lib/python3.11/site-packages/ultralytics/utils/metrics.py", line 319, in process_cls_preds
    self.matrix[p][t] += 1
    ~~~~~~~~~~~~~~^^^
IndexError: index 8 is out of bounds for axis 0 with size 2
Exception in thread Thread-2 (_pin_memory_loop):
Traceback (most recent call last):
  File "/home/datpham/.conda/envs/plant/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
